### ISSUE TITLE
Getting "No active package rename"

### ISSUE THREAD

**Issue by buttonsrtoys** [onatcipli/rename#13]
From my root folder I'm running: pub global run rename --bundleId com.dreamalytics.dreamapp which gives me the response "No active package rename". What does that mean?

**Comment by Entrepreter** [comment]
try `flutter pub global run rename --bundleId com.dreamalytics.dreamapp`

**Comment by buttonsrtoys** [comment]
Ah. Of course. Thanks!

**Comment by onatcipli** [comment]
It is related to the dart paths and has been solved I think, I closing this ✌️

@Entrepreter  Thanks for the info 🙏

**Comment by rignaneseleo** [comment]
I get the same error:
```
> opentabu % flutter pub global run rename --bundleId rignanese.leo.speakeasy 
No active package rename.
pub finished with exit code 65
```

**Comment by Metwally2020** [comment]
what worked for me, was after installing the package, and running " flutter pub get ", now activate the package by running this command: " flutter pub global activate rename " Then you can use the package.

so the steps again are :
1- flutter pub add rename
2- flutter pub get 
3- flutter pub global activate rename
4- flutter pub global run rename --appname "YOUR APP NAME"
