### ISSUE TITLE
Resolving dependencies fail  : incompatible with flutter_markdown

### ISSUE THREAD

**Issue by javierbm7** [onatcipli/rename#18]
Today with new Flutter version fail :(

Because markdown 4.0.0 depends on args ^2.0.0 and no versions of markdown match >4.0.0 <5.0.0, markdown ^4.0.0 requires args ^2.0.0.
And because rename >=1.0.7 depends on args ^1.5.2, rename >=1.0.7 is incompatible with markdown ^4.0.0.
And because flutter_markdown 0.6.0 depends on markdown ^4.0.0 and no versions of flutter_markdown match >0.6.0 <0.7.0, rename >=1.0.7 is incompatible with flutter_markdown ^0.6.0.
So, because ciber_app depends on both flutter_markdown ^0.6.0 and rename ^1.2.0, version solving failed.
pub get failed (1; So, because ciber_app depends on both flutter_markdown ^0.6.0 and rename ^1.2.0, version solving failed.)

**Comment by PiN73** [comment]
Same with other apps packages that depends on args: `^2.0.0`, for example:

```yaml
dev_dependencies:
  rename: ^1.2.0
  flutter_launcher_icons: ^0.9.0
```

```
% flutter pub get
Because flutter_launcher_icons >=0.9.0 depends on args 2.0.0 and rename >=1.0.7 depends on args ^1.5.2, flutter_launcher_icons >=0.9.0 is incompatible with rename >=1.0.7.
So, because myapp depends on both rename ^1.2.0 and flutter_launcher_icons ^0.9.0, version solving failed.
Running "flutter pub get" in myapp...                                   
pub get failed (1; So, because myapp depends on both rename ^1.2.0 and
flutter_launcher_icons ^0.9.0, version solving failed.)
```
