### ISSUE TITLE
zsh: command not found: rename

### ISSUE THREAD

**Issue by natanloterio** [onatcipli/rename#2]
Hi there, i just followed the instructions:

`$ pub global activate rename`
`$ rename`

But I got this error instead:
`zsh: command not found: rename`

Can you give me a hint on that?

**Comment by dexcell** [comment]
You should add to you zsh profile, as instructed.
I just install this package, looks good.
If you on mac like me.
````
open ~/.zshrc
````
Add
````
export PATH="$PATH":"$HOME/.pub-cache/bin"
````
Save the file,
Open new terminal and `cd`  to your project root, and rename should work

**Comment by onatcipli** [comment]
Also, you can check the following site for adding pub to your path

https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path

**Comment by onatcipli** [comment]
since it is not related to this package, I'm closing it
