### ISSUE TITLE
<application> tag was removed by rename --appname 

### ISSUE THREAD

**Issue by Yleisnero** [onatcipli/rename#23]
This line: 
`<application android:label="myAppName" android:icon="@mipmap/ic_launcher">`
was replaced by:
`myNewAppName`

I was running: flutter pub global run rename --appname "myNewAppName" in VS Code.

**Comment by Syed-Waleed-Shah** [comment]
**This package is what you need 🔥 Too much flexibilities <br>**
https://pub.dev/packages/rename_app <br>
*Rename App The only flutter package which changes app name for all platforms with sound null safety! If you want to autmatically change your flutter app name with a single command then you are at the right pacakge. This package gives you too many flexibilities through too many variants of its commands. Read the details below to know in more details*

**✊ Dont forget to star the github repo if you found this package useful 😇** 

**Features 🔥** <br>
✅ Remane Android Project <br> ✅ Remane IOS Project <br> ✅ Remane WEB Project <br> ✅ Remane Windows Project

**How To Rename ? 🛠**

**1) ADD THE PACKAGE TO DEPENDENCIES IN pubspec.yaml** 
<br>`flutter pub add rename_app `
<br>
OR
<br>
`dependencies: 
   rename_app: ^latest_version` <br><br>
**2) PROVIDE THE APP NAME <br>**
You can provide app name in the following ways

 - Same name for all apps<br>

> `flutter pub run rename_app:main all="My App Name"`

 - Seperate name for specified platform(s) and same for all others <br>

> `flutter pub run rename_app:main android="Anroid Name" ios="IOS Name"
> others="Others Name"`

 - Seperate name for each platform <br>

> `flutter pub run rename_app:main android="Android Name" ios="IOS Name"
> web="Web Name" mac="Mac Name" windows="Windows Name"`

**Comment by onatcipli** [comment]
PR merged, it should be fine now. If you face the issue again feel free to open!
