### ISSUE TITLE
Android manifest package not changed.

### ISSUE THREAD

**Issue by RoarGronmo** [onatcipli/rename#32]
Tried to use the tool to change bundleId, and I see that android manifest old package name stays put.

**Comment by Syed-Waleed-Shah** [comment]
**This package is what you need 🔥 Too much flexibilities <br>**
https://pub.dev/packages/rename_app <br>
*Rename App The only flutter package which changes app name for all platforms with sound null safety! If you want to autmatically change your flutter app name with a single command then you are at the right pacakge. This package gives you too many flexibilities through too many variants of its commands. Read the details below to know in more details*

**✊ Dont forget to star the github repo if you found this package useful 😇** 

**Features 🔥** <br>
✅ Remane Android Project <br> ✅ Remane IOS Project <br> ✅ Remane WEB Project <br> ✅ Remane Windows Project

**How To Rename ? 🛠**

**1) ADD THE PACKAGE TO DEPENDENCIES IN pubspec.yaml** 
<br>`flutter pub add rename_app `
<br>
OR
<br>
`dependencies: 
   rename_app: ^latest_version` <br><br>
**2) PROVIDE THE APP NAME <br>**
You can provide app name in the following ways

 - Same name for all apps<br>

> `flutter pub run rename_app:main all="My App Name"`

 - Seperate name for specified platform(s) and same for all others <br>

> `flutter pub run rename_app:main android="Anroid Name" ios="IOS Name"
> others="Others Name"`

 - Seperate name for each platform <br>

> `flutter pub run rename_app:main android="Android Name" ios="IOS Name"
> web="Web Name" mac="Mac Name" windows="Windows Name"`

**Comment by Trulsmatias** [comment]
Bumping this

**Comment by onatcipli** [comment]
Can you provide more details please ?

**Comment by RoarGronmo** [comment]
Oh, wow, it's over a year since i tried it... I'm afraid I cannot remember the details now, please give some time, I may recall it.

**Comment by onatcipli** [comment]
@RoarGronmo maybe it is already fixed with the latest version `2.1.1`. Please let me know and feel free to open issue again if you face it again.

**Comment by RoarGronmo** [comment]
I'll do.

**Comment by codemagic-mohammed** [comment]
What @RoarGronmo meant was that when trying to change the Android `bundleId` (package name) the plugin only renames the `applicationId` in `build.gradle` file, but it's not changing the `package` property inside the `AndroidManifest.xml` file.

I think it's important to change the value in the `AndroidManifest.xml` as well so the app counted to be identified by the new package name.

**Comment by afzl-wtu** [comment]
Still not fixed
