### ISSUE TITLE
CFBundleDisplayName not updating

### ISSUE THREAD

**Issue by theyokohamalife** [onatcipli/rename#37]
Inside the Info.plist there is a `<key>CFBundleDisplayName</key>` and a `<key>CFBundleName</key>`. 

Running `rename --appname yourappname -t ios` will only update the `<key>CFBundleName</key>`. 

Is there a way to change both using this package so they're the same?

**Comment by AGliddon** [comment]
This is a major issue for us too. 

CFBundleName is mostly ignored in favour of CFBundleDisplayName. The latter is used as the app title for the icon on the iOS home screen as well as all system popups that refer to the app by name.

**Comment by myfknoll** [comment]
Same here

**Comment by onatcipli** [comment]
The PR merged thanks for the effort please get the `2.1.1` version
