### ISSUE TITLE
[Old Dependencies]. rename 2.1.1 depends on logger ^1.1.0

### ISSUE THREAD

**Issue by XeroDays** [onatcipli/rename#48]
Please upgrade the dependencies  for logger

`logger: ^2.0.1`

## Error:
<img width="952" alt="image" src="https://github.com/onatcipli/rename/assets/38852291/6f40a202-4585-4387-b4cb-880bfc8d9065">

**Comment by onatcipli** [comment]
It has been fixed after `v3.0.1`
