### ISSUE TITLE
Windows, setAppName does not work when window.CreateAndShow is used

### ISSUE THREAD

**Issue by gourgouris** [onatcipli/rename#50]
When I try to use setAppName for a windows target, if my code has `window.CreateAndShow` instead of `window.Create`, once the tool is run, it replaces the name but also it replaces `CreateAndShow` with `Create`.
I think there is a typo in this line: https://github.com/onatcipli/rename/blob/b082e05fe2c68b7cb59f4844087022fd5d339b96/lib/platform_file_editors/windows_platform_file_editor.dart#L87
Shouldn't it be `return 'CreateAndShow(L"$appName"';`

**Comment by onatcipli** [comment]
Hey @gourgouris , thank you for reporting this can you try with the latest version I have fix for it ✌️ 

`version 3.0.1`

Please reopen the issue if it isn't fixed
