### ISSUE TITLE
"The syntax of the command is incorrect" is the only response to anything.

### ISSUE THREAD

**Issue by ScottS2017** [onatcipli/rename#52]
Regardless of what command is attempted, the response is always that the syntax is incorrect. This also happens when using copy/paste commands out of the readme. I've deactivated and reactivated, it hasn't helped.
![image](https://github.com/onatcipli/rename/assets/32370328/948642b5-4ae2-41a1-8d5f-39ff5e928b80)

**Comment by lostest4352** [comment]
If you're using cmd, try powershell. I had this same problem with cmd but it works in powershell.

**Comment by teerasej** [comment]
@lostest4352 I found that using powershell also found this problem. Do you need to run the Powershell as Administrator?

**Comment by MuhamadHaydar** [comment]
i have same issue, it always says the following: 

command not found: rename

**Comment by onatcipli** [comment]
Hello guys, @MuhamadHaydar  thank you for the response and feedback I think it is related to some windows configuration but I just double check again to run via `flutter pub run rename` or `dart run rename` both are fine to go with please let me know if you are still having the same issue via this prefixes @ScottS2017 @teerasej 

I also created Troubleshooting section in readme which may help others 

> 
> ## Troubleshooting
> 
> #### Command Not Working on Windows
> 
> If you encounter issues running the `rename` command directly in Windows, especially from a non-administrator terminal, you might need to use an alternative command format. This issue can arise due to permission restrictions or path variable misconfigurations.
> 
> Try executing the command using one of the following formats:
> 
> - Using Flutter:
>   ```sh
>   flutter pub run rename <command> [arguments]
>   ```
> - Using Dart:
>   ```sh
>   dart run rename <command> [arguments]
>   ```
> 
> These alternative commands explicitly invoke the `rename` tool through the Dart or Flutter toolchain, which can bypass some of the path or permission issues encountered in certain Windows configurations.
