### ISSUE TITLE
Incorrect command syntax

### ISSUE THREAD

**Issue by praneshp1org** [onatcipli/rename#53]
![image](https://github.com/onatcipli/rename/assets/80845871/460a0592-1178-4c67-b966-289ab817557c)

I had previously used the same package to change the app name and bundleID, however now it doesn't seem to work..

**Comment by mirkancal** [comment]
https://github.com/onatcipli/rename/issues/52#issuecomment-1842203473

**Comment by onatcipli** [comment]
Hey @praneshp1org, can you refer to new readme please the usages has changed

    rename setAppName --targets ios,android --value "YourAppName"
